name: bfproperty
description: BF-property

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  firebase_core: ^1.0.2
  firebase_analytics: ^8.2.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  flutter_svg: ^0.22.0
  introduction_screen: ^2.1.0
  google_sign_in:
  flutter_facebook_auth:
  # apple_sign_in:
  get: ^4.1.3
  get_storage: ^2.0.2
  http: ^0.13.1
  flutter_map: ^0.13.1
  # flutter_platform_widgets:
  flutter_sheet_localization: ^5.1.1
  simple_gravatar:
  flutter_share: ^2.0.0
  material_design_icons_flutter: ^4.0.5955
  line_awesome_flutter: ^1.0.1
  email_validator: ^2.0.1
  inspection: ^0.0.11
  flutter_dotenv: ^5.0.0
  flutter_multi_formatter: ^2.3.1
  flutter_thailand_provinces: 1.0.1
  flutter_typeahead: ^3.2.0
  latlng: ^0.1.0
  latlong2: ^0.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
 

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/images/
    - assets/icons/
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages